### ISSUE TITLE
Menu Keyboard Focus Order

### ISSUE THREAD

**Issue by brionwolf** [UMD-Digital/elements-utility-header#1]
Keyboard focus on small/mobile screens follows same order of items as on desktop/larger screens. UX wise, I thought it was broken till i tabbed past the _end_ of the menu.

![umd-header-keyboard-focus-order](https://user-images.githubusercontent.com/5532234/125334346-47030580-e319-11eb-9b01-e68954709e1f.gif)

**Comment by magnessjo** [comment]
The design needs to change to make it work on both viewports (or else we are adding two different forms which isn't best practices either).
