### ISSUE TITLE
Search form tab-able when hidden on desktop

### ISSUE THREAD

**Issue by brionwolf** [UMD-Digital/elements-utility-header#6]
Steps
------

1. Access site with utility header on a desktop sized screen
2. Make sure the header includes the _search_ feature
3. Set focus to the university name
4. tab to the search button (with the magnifying glass)
5. Continue to tab through

`Expected:` On desktop, the search button is the last item in the header, and I assume I would continue onto the page content
`Result:` You need to press tab two more times before getting past header content. Voiceover indicates the two extra elements getting focus are the hidden search input field, and hidden submit button.

Screencaps
---------------
![animated gif of user tabbing through the elements in the utility header](https://user-images.githubusercontent.com/5532234/161066884-7c775c40-c24f-42d0-a58d-9d6daddffa80.gif)

**Comment by magnessjo** [comment]
@brionwolf should be fixed with 1.0.1 - Please verify and close out if so.

**Comment by magnessjo** [comment]
Fixed with 1.0.2 - https://github.com/UMD-Digital/elements-utility-header/commit/bb715b63198692317dbb8aaaf7f7c02412652e41

**Comment by brionwolf** [comment]
Confirmed! works on [brand.umd-staging.com](https://brand.umd-staging.com), Thanks!
